# Set defaults for fastp-rules rules on cluster.
# Last modified: tor jan 13, 2022  01:52
# Sign: JN
# IMPORTANT: Adjust the account number below.

__default__:
    account: "snic1234-5-678"
    partition: "core"
    time: "01:00:00"
    output: "slurm/stdout/{rule}.{wildcards}.out"
    error: "slurm/stderr/{rule}.{wildcards}.err"
    jobname: "\'[{rule}]: {wildcards}\'"

fastp:
    cpus-per-task: 4
    time: "01:00:00"

