#########################
# Run configuration
#########################
inputdir: "input"
input_fn_pattern: "{sample}_{readpair}_001.fastq.gz"
outdir: "output"
logdir: "output/logs"
report: "output/fastp-cleaning-report-"

#########################
# Pipeline steps included
#########################
run_fastp: True
fastp_merge: False
multiqc_report: False

#########################
# Extra options to tools
#########################
fastp:
    extra: "--detect_adapter_for_pe --correction --cut_right"
    n: 4
multiqc:
    extra: ""

