# Run configuration
inputdir:   "input"
fn_pattern: "{sample}_{readpair}_001.fastq.gz"
outputdir:  "output"
fastadir:   "output/fasta"
fastpdir:   "output/fastp"
fastqdir:   "output/fastq"
logdir:     "output/logs"
report:     "output/workflow-report-"

# Workflow steps
run_fastp:          True
run_fastp_dedup:    True
run_fastp_merge:    True
run_fastq_to_fasta: True

# Extra options to tools
# fastp
fastp:
    extra: "--detect_adapter_for_pe --correction --cut_right "
    n: 4
    dup_calc_accuracy: 3

# fastq_to_fasta using seqtk seq
fastq_to_fasta:
    extra: ""
    n: 1

# tab_to_fasta using seqkit
tab_to_fasta:
    extra: "-t dna"
    n: 4
