# Run configuration
inputdir: "input"
input_fn_pattern: "{sample}_{readpair}_001.fastq.gz"
input_fqgz_pattern: "{sample}_{readpair}.fq.gz"
output_fas_pattern: "{sample}_{readpair}.fas"
outputdir: "output"
fastqdir: "output/fastq"
fastadir: "output/fasta"
logdir: "output/logs"
report: "output/fastp-cleaning-report-"

# Workflow steps
run_fastp: True
fastp_dedup: True
fastp_merge: True
fastq_to_fasta: True
module: False

# Extra options to tools
# fastp
fastp:
    extra: "--detect_adapter_for_pe --correction --cut_right "
    n: 4
    dup_calc_accuracy: 3
# seqtk
seqtk:
    extra: ""
    n: 1
# seqkit
seqkit:
    extra: "-t dna"
    n: 4
