#########################
# Run configuration
#########################
inputdir: "input"
input_fn_pattern: "{sample}_{readpair}_001.fastq.gz"
outdir: "output"
logdir: "output/logs"
#report: "output/fastp-cleaning-report-"

#########################
# Pipeline steps included
#########################
run_fastp: True
fastp_dedup: True
fastp_merge: False
fastq_to_fasta: False
multiqc_report: False

#########################
# Extra options to tools
#########################
fastp:
    extra: "--detect_adapter_for_pe --correction --cut_right "
    n: 4
    dup_calc_accuracy: 3
multiqc:
    extra: ""
seqtk:
    extra ""
